# Generated by Django 5.1.1 on 2024-10-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_image_about_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image2',
            field=models.ImageField(default='path_to_default_image.jpg', upload_to=''),
        ),
    ]
